In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/AB_US_2024.csv", low_memory=False)

In [3]:
df.shape

(232147, 18)

In [4]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,city
0,958.0,"Bright, Modern Garden Unit - 1BR/1BTH",1169,Holly,NaN,Western Addition,37.77028,-122.43317,Entire home/apt,202,2,383,2/19/2023,2.31,1,128,59,San Francisco
1,5858.0,Creative Sanctuary,8904,Philip And Tania,NaN,Bernal Heights,37.74474,-122.42089,Entire home/apt,235,30,111,8/6/2017,0.66,1,365,0,San Francisco
2,8142.0,Friendly Room Apt. Style -UCSF/USF - San Franc...,21994,Aaron,NaN,Haight Ashbury,37.76555,-122.45213,Private room,56,32,9,10/27/2022,0.09,13,365,1,San Francisco
3,8339.0,Historic Alamo Square Victorian,24215,Rosy,NaN,Western Addition,37.77564,-122.43642,Entire home/apt,575,9,28,6/28/2019,0.17,2,365,0,San Francisco
4,8739.0,"Mission Sunshine, with Private Bath",7149,Ivan & Wendy,NaN,Mission,37.76030,-122.42197,Private room,110,1,770,2/25/2023,4.65,2,159,34,San Francisco

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 232147 entries, 0 to 232146
Data columns (total 18 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              232147 non-null  float64
 1   name                            232131 non-null  str
 2   host_id                         232147 non-null  int64
 3   host_name                       232134 non-null  str
 4   neighbourhood_group             96500 non-null   str
 5   neighbourhood                   232147 non-null  str
 6   latitude                        232147 non-null  float64
 7   longitude                       232147 non-null  float64
 8   room_type                       232147 non-null  str
 9   price                           232147 non-null  int64
 10  minimum_nights                  232147 non-null  int64
 11  number_of_reviews               232147 non-null  int64
 12  last_review                     183062 non-null  str
 13  reviews_per_month               183062 non-null  float64
 14  calculated_host_listings_count  232147 non-null  int64
 15  availability_365                232147 non-null  int64
 16  number_of_reviews_ltm           232147 non-null  int64
 17  city                            232147 non-null  str
dtypes: float64(4), int64(7), str(7)
memory usage: 53.5 MB

In [6]:
df.isnull().sum()

id                                     0
name                                  16
host_id                                0
host_name                             13
neighbourhood_group               135647
neighbourhood                          0
latitude                               0
longitude                              0
room_type                              0
price                                  0
minimum_nights                         0
number_of_reviews                      0
last_review                        49085
reviews_per_month                  49085
calculated_host_listings_count         0
availability_365                       0
number_of_reviews_ltm                  0
city                                   0
dtype: int64

In [7]:
print("Duplicate Rows :", df.duplicated().sum())

df.drop_duplicates(inplace=True)

Duplicate Rows : 153

In [8]:
df.info()

<class 'pandas.DataFrame'>
Index: 231994 entries, 0 to 232146
Data columns (total 18 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              231994 non-null  float64
 1   name                            231978 non-null  str
 2   host_id                         231994 non-null  int64
 3   host_name                       231981 non-null  str
 4   neighbourhood_group             96496 non-null   str
 5   neighbourhood                   231994 non-null  str
 6   latitude                        231994 non-null  float64
 7   longitude                       231994 non-null  float64
 8   room_type                       231994 non-null  str
 9   price                           231994 non-null  int64
 10  minimum_nights                  231994 non-null  int64
 11  number_of_reviews               231994 non-null  int64
 12  last_review                     183060 non-null  str
 13  reviews_per_month               183060 non-null  float64
 14  calculated_host_listings_count  231994 non-null  int64
 15  availability_365                231994 non-null  int64
 16  number_of_reviews_ltm           231994 non-null  int64
 17  city                            231994 non-null  str
dtypes: float64(4), int64(7), str(7)
memory usage: 55.3 MB

In [9]:
df["last_review"] = pd.to_datetime(df["last_review"], errors="coerce")

numeric_cols = [
    "price",
    "minimum_nights",
    "number_of_reviews",
    "reviews_per_month",
    "calculated_host_listings_count",
    "availability_365",
    "number_of_reviews_ltm",
    "latitude",
    "longitude"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [10]:
numeric_fill = [
    "price",
    "minimum_nights",
    "reviews_per_month",
    "latitude",
    "longitude"
]

for col in numeric_fill:
    df[col] = df[col].fillna(df[col].median())

In [11]:
text_cols = [
    "name",
    "host_name",
    "neighbourhood_group",
    "neighbourhood",
    "room_type",
    "city"
]

for col in text_cols:
    df[col] = df[col].fillna("Unknown")

In [12]:
df.isnull().sum()

id                                    0
name                                  0
host_id                               0
host_name                             0
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       48934
reviews_per_month                     0
calculated_host_listings_count        0
availability_365                      0
number_of_reviews_ltm                 0
city                                  0
dtype: int64

In [13]:
# outlier

df = df[(df["price"] >= 20) & (df["price"] <= 2000)]

In [14]:
df = df[df["minimum_nights"] > 0]

In [15]:
df = df[
    df["latitude"].between(-90,90) &
    df["longitude"].between(-180,180)
]

In [16]:
print(df.shape)

df.describe()

(229806, 18)

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm
count,2.298060e+05,2.298060e+05,229806.000000,229806.000000,229806.000000,229806.000000,229806.000000,182109,229806.000000,229806.000000,229806.000000,229806.000000
mean,2.579734e+17,1.578344e+08,36.626297,-98.231388,213.579558,13.507485,41.225051,2022-06-02 23:57:41.463189,1.509644,29.588039,180.852406,11.787952
min,6.000000e+00,2.300000e+01,25.957323,-123.089130,20.000000,1.000000,0.000000,2010-10-04 00:00:00,0.010000,1.000000,0.000000,0.000000
25%,2.632402e+07,2.292872e+07,33.976550,-118.313205,90.000000,2.000000,1.000000,2022-08-15 00:00:00,0.450000,1.000000,52.000000,0.000000
50%,4.894517e+07,1.002381e+08,36.197665,-97.724425,149.000000,3.000000,9.000000,2023-01-21 00:00:00,1.000000,2.000000,175.000000,3.000000
75%,6.623812e+17,2.677370e+08,40.718180,-77.023702,249.000000,30.000000,43.000000,2023-03-04 00:00:00,2.000000,10.000000,320.000000,16.000000
max,8.581010e+17,5.069384e+08,47.734010,-70.996000,2000.000000,1250.000000,3091.000000,2023-03-31 00:00:00,101.420000,1003.000000,365.000000,1314.000000
std,3.463920e+17,1.585205e+08,5.132449,19.717810,225.131330,27.862280,80.881657,NaN,1.721259,106.040086,134.584324,20.659554

In [17]:
df.to_excel(
    "../data/ABNCleanexcel_data.xlsx",
    index=False,
    engine="openpyxl"
)

In [18]:
df.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'city'],
      dtype='str')